[project]
name = "py-omop2neo4j-lpg"
version = "0.1.0"
description = "A Python package to migrate OMOP vocabulary tables from PostgreSQL to Neo4j."
authors = [{ name = "Gowtham Rao", email = "rao@ohdsi.org" }]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "psycopg2-binary",
    "neo4j",
    "pandas",
    "numpy",
    "click",
    "pydantic-settings",
    "python-dotenv",
]

[project.scripts]
omop2neo4j = "omop2neo4j_lpg.cli:main"
