[project]
name = "py-omop2neo4j-lpg"
version = "0.1.0"
description = "A Python package to migrate OMOP vocabulary from PostgreSQL to Neo4j."
authors = [{ name = "Gowtham Rao", email = "rao@ohdsi.org" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "psycopg2-binary",
    "neo4j",
    "pandas",
    "numpy",
    "click",
    "pydantic-settings",
    "python-dotenv",
]

[project.scripts]
py-omop2neo4j-lpg = "omop2neo4j_lpg.cli:main"
